[2024-11-03T08:41:56.245+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-03T08:41:56.260+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: job_scraping_pipeline.scraping_tasks.scrape_chunk_8 manual__2024-11-03T08:41:06.578940+00:00 [queued]>
[2024-11-03T08:41:56.269+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: job_scraping_pipeline.scraping_tasks.scrape_chunk_8 manual__2024-11-03T08:41:06.578940+00:00 [queued]>
[2024-11-03T08:41:56.270+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 4
[2024-11-03T08:41:56.292+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): scraping_tasks.scrape_chunk_8> on 2024-11-03 08:41:06.578940+00:00
[2024-11-03T08:41:56.306+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'job_scraping_pipeline', 'scraping_tasks.scrape_chunk_8', 'manual__2024-11-03T08:41:06.578940+00:00', '--job-id', '102', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmpv2625xc5']
[2024-11-03T08:41:56.309+0000] {standard_task_runner.py:105} INFO - Job 102: Subtask scraping_tasks.scrape_chunk_8
[2024-11-03T08:41:56.311+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=711) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-03T08:41:56.312+0000] {standard_task_runner.py:72} INFO - Started process 716 to run task
[2024-11-03T08:41:56.356+0000] {task_command.py:467} INFO - Running <TaskInstance: job_scraping_pipeline.scraping_tasks.scrape_chunk_8 manual__2024-11-03T08:41:06.578940+00:00 [running]> on host 6fb5d61061dc
[2024-11-03T08:41:56.447+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='job_scraping_pipeline' AIRFLOW_CTX_TASK_ID='scraping_tasks.scrape_chunk_8' AIRFLOW_CTX_EXECUTION_DATE='2024-11-03T08:41:06.578940+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-03T08:41:06.578940+00:00'
[2024-11-03T08:41:56.449+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-03T08:41:56.469+0000] {main_scrap.py:318} ERROR - 主程序執行錯誤: JobScraper.__init__() got an unexpected keyword argument 'request_timeout'
[2024-11-03T08:41:56.470+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 762, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/tasks/main_scrap.py", line 291, in web_crawler
    scraper = JobScraper(
              ^^^^^^^^^^^
TypeError: JobScraper.__init__() got an unexpected keyword argument 'request_timeout'
[2024-11-03T08:41:56.485+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=job_scraping_pipeline, task_id=scraping_tasks.scrape_chunk_8, run_id=manual__2024-11-03T08:41:06.578940+00:00, execution_date=20241103T084106, start_date=20241103T084156, end_date=20241103T084156
[2024-11-03T08:41:56.504+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-03T08:41:56.505+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 102 for task scraping_tasks.scrape_chunk_8 (JobScraper.__init__() got an unexpected keyword argument 'request_timeout'; 716)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 762, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/tasks/main_scrap.py", line 291, in web_crawler
    scraper = JobScraper(
              ^^^^^^^^^^^
TypeError: JobScraper.__init__() got an unexpected keyword argument 'request_timeout'
[2024-11-03T08:41:56.527+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-03T08:41:56.558+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-03T08:41:56.559+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
